### PR TITLE
Add ability to define rules dynamically

### PR DESCRIPTION
**Pull request by mkuklis**
Hi @domagojk I really like `redux-orchestrate` and its simplicity. I ran into a situation where I need to define rules dynamically (the `processManager` is empty when the middleware is configured). This PR introduces a way to add rules in a dynamic fashion:
````js
const store = createStore(reducer, applyMiddleware(orchestrate()))

// ...

const rules = [{
    case: 'TEST',
    dispatch: ['FIRST', 'SECOND']
}]

orchestrate.addRules(rules)

````

Would you consider adding it? 

Thank you again for this great lib!

### CODE REVIEW

**Comment by domagojk** [comment]
Thank you @mkuklis, it looks good!
I will try (and probably publish) it tomorrow :)

**Comment by mkuklis** [comment]
@domagojk thank you! That would be great!

**Comment by domagojk** [comment]
@mkuklis I had to change your PR a bit
`orchestrate` is a factory for creating middlewares and since it's possible to create multiple middlewares with it, I think it's not a good idea to bind `config` on it.

So I added `addRules` to middleware function instead (one that is created with `orchestrate`) and also modified some tests for it.

And since this would be advanced feature IMO, I moved its documentation in separate paragraph at the end of "usage" section.

**Comment by mkuklis** [comment]
@domagojk that makes sense. Thank you for changing it and releasing a new version!

**Pull request merged**
